import type { OpenProps } from '../types';
export function Header({onOpen}: OpenProps) { return (<header><a className="logo" href="#home">a<span>v</span><sup>®</sup></a><nav><a href="#work">Selected work</a><a href="#ai-lab">AI lab</a><a href="#experience">Experience</a><a href="#about">About</a></nav><button onClick={() => onOpen('resume')} className="outline">Résumé ↗</button></header>); }
export function Hero({onOpen}: OpenProps) { return (<section id="home" className="hero"><div className="eyebrow-row"><p className="eyebrow">● ABHINAV REDDY VARIMALLA / SOFTWARE ENGINEER</p><button onClick={() => onOpen('commands')} className="shortcut" aria-label="Open navigation commands">⌘ K <span>Explore</span></button></div><div className="hero-grid"><div><p className="kicker">JAVA & SPRING · GO DEVELOPMENT · AI ENGINEERING</p><h1>Reliable systems.<br /><em>Intelligent experiences.</em></h1><p className="description">I’m Abhinav, an Application Developer at Oracle. My work spans enterprise Java systems, with personal projects in Go service reliability and AI applications built with Python and RAG.</p><div className="actions"><a className="button" href="#work">Explore my work ↗</a><a href="#ai-lab">Explore the AI lab ↓</a></div><div className="signature"><span>SOFTWARE ENGINEER.<br />GO DEVELOPER. AI BUILDER.</span><span>ORACLE / HYDERABAD<br />JAVA · GO · AI APPLICATIONS</span></div></div><div className="orbital" aria-hidden="true"><span className="orbit-caption">SYSTEMS THINKING / 001</span><div className="glow"></div><div className="ring one"></div><div className="ring two"></div><div className="ring three"></div><div className="core">&#123;<b>av</b>&#125;</div><span className="sat s1">JAVA ↗</span><span className="sat s2">GO ◈</span><span className="sat s3">AI ⌘</span><div className="orbit-footer">01 — REQUEST &nbsp; &nbsp; 02 — REASON &nbsp; &nbsp; 03 — BUILD</div></div></div><div className="hero-footer"><span>SCROLL TO EXPLORE</span><span>↓</span><span>PORTFOLIO / DESIGN EDITION 03</span></div></section>); }
export function About({onOpen}: OpenProps) { return (<section className="about" id="about"><div><p className="eyebrow">04 / THE PERSON BEHIND THE CODE</p><h2>Production experience.<br /><em>A builder’s curiosity.</em></h2><p className="description">I’m Abhinav Reddy Varimalla, a software engineer with 2+ years at Oracle developing Java and database enhancements for enterprise utility systems.</p><p className="muted">Outside that work, my projects explore Go service reliability, Spring Boot observability, and Python-based RAG applications. I bring the same curiosity to troubleshooting a production issue and designing a new service.</p><button onClick={() => onOpen('resume')} className="outline">Explore my background ↗</button></div><div className="learning"><small>EDUCATION & RECOGNITION <em>●</em></small><div><span>01</span><article><h3>B.E. Computer Science</h3><p>Vasavi College of Engineering · 2020–2024</p></article>↗</div><div><span>02</span><article><h3>GPA: 9.05 / 10</h3><p>Qualified GATE during third year</p></article>↗</div><div><span>03</span><article><h3>Young Excellence Award</h3><p>Oracle · 2025</p></article>↗</div><footer><small>ENGINEERING FOCUS</small><p>Java & Spring · Go development · AI engineering</p></footer></div></section>); }
export function Contact({onOpen}: OpenProps) { return (<section className="contact" id="contact"><p className="eyebrow">05 / WHAT’S NEXT?</p><div><h2>Good things start<br />with a <em>conversation.</em></h2><button className="contact-arrow" onClick={() => onOpen('contact')} aria-label="Contact information">↗</button></div><p className="muted">A new idea. A technical conversation. A chance to build something useful.</p><div className="contact-links"><a href="mailto:abhinavreddyvarimalla@gmail.com">Email me ↗</a><a href="https://www.linkedin.com/in/abhinav-reddy-440b3b280/" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="Abhinav_resume.pdf" download>Download résumé ↓</a></div></section>); }
export function Toolkit(){return (<div className="toolkit"><small>THE TOOLKIT</small><strong>Java</strong><i>✳</i><strong>Spring Boot</strong><i>✳</i><strong>PostgreSQL</strong><i>✳</i><strong>Go</strong><i>✳</i><strong>Python / RAG</strong><i>✳</i><strong>LangChain</strong><i>✳</i><strong>LangGraph</strong></div>);}
export function Experience(){return (<section id="experience"><p className="eyebrow">03 / PROFESSIONAL EXPERIENCE</p><div className="heading"><h2>Engineering for<br /><em>real-world operations.</em></h2><p>Oracle Utilities Network Management System<br />Hyderabad, India<br />August 2024 – Present</p></div><div className="experience-card"><div><span className="badge">ORACLE</span><h3>Application Developer</h3><p>Java · SQL · PL/SQL · Enterprise utility systems</p></div><ul><li>Develop enhancements across outage management, switching, SCADA, power-flow, FLISR, and feeder-load management workflows.</li><li>Investigate production and test failures by correlating logs, database records, configuration, and runtime behavior.</li><li>Built Flexie, an OJET-based chatbot for FLEX, reducing manual work by 30%.</li><li>Validate deployments and post-release changes; collaborate on requirements, defect reviews, and production issue resolution.</li></ul></div></section>);}
export function Footer(){return (<footer className="footer"><a href="#home" className="logo">a<span>v</span><sup>®</sup></a><span>ABHINAV VARIMALLA © 2026</span><span>BUILT WITH INTENTION.</span><a href="#home">Back to top ↑</a></footer>);}

export function EngineeringFocus({onOpen}: OpenProps){return <section className="engineering-focus" aria-labelledby="focus-title"><p className="eyebrow">THREE DISCIPLINES / ONE ENGINEERING MINDSET</p><div className="heading"><h2 id="focus-title">Systems that work.<br /><em>Ideas that learn.</em></h2><p>Enterprise experience and independent projects.<br />Explore the engineering behind each.</p></div><div className="focus-grid">{[
{n:'01',title:'Java & Spring',label:'BACKEND ENGINEERING',text:'Enterprise Java experience at Oracle, alongside a Spring Boot observability project exploring logs, metrics, and traces.',tags:'Java · Spring Boot · SQL · Kafka',panel:'products' as const,link:'Explore observability'},
{n:'02',title:'Go developer',label:'CONCURRENT SYSTEMS',text:'Reliable webhook delivery with bounded goroutine workers, durable jobs, lease recovery, and retries that account for failure.',tags:'Go · PostgreSQL · Concurrency · HMAC',panel:'orders' as const,link:'Explore webhook delivery'},
{n:'03',title:'AI engineering',label:'CONTEXT-AWARE APPLICATIONS',text:'Résumé-aware interview questions using retrieval-augmented generation, with Python and Hugging Face models.',tags:'Python · RAG · PyTorch · Hugging Face',panel:'interviewer' as const,link:'Explore the AI interviewer'}
].map(item=><article className="focus-card" key={item.n}><div className="focus-index"><span>{item.n}</span><small>{item.label}</small></div><h3>{item.title}</h3><p>{item.text}</p><small className="focus-tags">{item.tags}</small><button className="outline" onClick={()=>onOpen(item.panel)}>{item.link} ↗</button></article>)}</div></section>;}
