CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL CHECK (CHAR_LENGTH(TRIM(name)) > 0),
    price NUMERIC(12,2) NOT NULL CHECK (price > 0),
    in_stock BOOLEAN NOT NULL DEFAULT TRUE
);
INSERT INTO products (name,price,in_stock) VALUES
('Mechanical keyboard',89.00,TRUE),
('Studio headphones',129.00,TRUE),
('Desk light',45.00,FALSE);
